myproject/core/urls.py
from django.urls import path
from myproject.core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.index, name="index"),
    path('repo/', v.repo_list, name="repo_list"),
    path('repo/json/', v.repo_json, name="repo_json"),
    path('repo/add/', v.repo_add, name="repo_add"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models


class Repo(models.Model):
    slug = models.BigIntegerField(
        unique=True,
        help_text='slug is id of github api'
    )
    name = models.TextField()
    full_name = models.TextField()
    html_url = models.URLField()
    stargazers_count = models.PositiveIntegerField()

    class Meta:
        ordering = ('-stargazers_count',)

    def __str__(self):
        return self.name

    def to_dict_json(self):
        return {
            'slug': self.slug,
            'name': self.name,
            'full_name': self.full_name,
            'html_url': self.html_url,
            'stargazers_count': self.stargazers_count,
        }

myproject/core/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .models import Repo


def index(request):
    template_name = 'core/index.html'
    return render(request, template_name)


def repo_list(request):
    template_name = 'core/repos_list.html'
    return render(request, template_name)


def repo_json(request):
    ''' Retorna um JSON dos repos. '''
    repos = Repo.objects.all()
    data = [item.to_dict_json() for item in repos]
    return JsonResponse({'data': data})


@csrf_exempt
def repo_add(request):
    if request.method == 'POST':
        Repo.objects.all().delete()
        response = request.POST
        items = json.loads(response['item'])
        aux = []
        for item in items:
            obj = Repo(
                slug=item['id'],
                name=item['name'],
                full_name=item['full_name'],
                html_url=item['html_url'],
                stargazers_count=item['stargazers_count'],
            )
            aux.append(obj)
        Repo.objects.bulk_create(aux)
        repos = Repo.objects.all()
        data = [item.to_dict_json() for item in repos]
        return JsonResponse({'data': data})

myproject/core/templates/base.html
<!-- https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template -->
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <title>API Github</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block css %}{% endblock css %}

  </head>
  <body>

    {% include "includes/nav.html" %}

    <div class="container">
      {% block content %}{% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- VueJS -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js"></script>
    <!-- Axios -->
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    {% block js %}{% endblock js %}
  </body>
</html>

myproject/core/templates/core/index.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1>Bem-vindo!</h1>
    <p>
      <a href="https://github.com/rg3915/aw-challenge" target="_blank">Veja no GitHub</a>
    </p>
  </div>
</div>

{% endblock content %}

myproject/core/templates/core/repos_list.html
{% extends "base.html" %}
{% load static %}

{% block css %}

  <style>
    body {
      margin-top: 70px;
    }
  </style>

{% endblock css %}

{% block content %}

<div id="app">
  <div class="row">
    <div class="row">
      <p>Do lado esquerdo você pode digitar um username do Github e clicar em listar que ele vai listar os repositórios na tela.</p>
      <p>Do lado direito ele busca pelos repositórios salvos no banco de dados.</p>
      <p>O botão 'Salvar todos' salva todos os repositórios no banco de dados.</p>
      <p>Clique no id para ver os detalhes.</p>
    </div>
    <div class="clearfix"></div>
    <div class="col-sm-8">
      <form action="." method="GET" class="form-inline">
        <label style="margin-right: 10px;">Digite o username</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="Ex: rg3915" v-model="username">
        <input class="btn btn-sm btn-primary" style="margin-left: 10px;" value="Listar" @click="getRepos(username)">
      </form>
    </div>
    <div class="col-sm-4">
      <form action="." method="GET" class="form-inline">
        <input type="text" id="search" name="search" class="form-control" placeholder="Busca" v-model="search">
        <input type="submit" class="btn btn-primary" style="margin-left: 10px;" value="OK">
      </form>
    </div>
  </div>

  <div class="page-header" style="margin-top: 15px;">
    <h2>Lista de Repositórios
      <form action="" method="POST" class="form-inline pull-right">
        <span>
          <a href="">
            <button type="button" class="btn btn-success" @click.prevent="saveRepos">
              <span class="fa fa-plus"></span> Salvar todos
            </button>
          </a>
        </span>
      </form>
    </h2>

    <table class="table table-striped">
      <thead>
        <tr>
          <th v-for="head in headers" :class="{'text-center': head.title == 'id' || head.title == 'stargazers_count'}">${ head.title }</th>
        </tr>
      </thead>
      <tbody>
        <template v-for="item in filteredItems">
          <tr>
            <td v-if="item.slug">
              <a href="#" data-toggle="modal" data-target="#myModal{{ forloop.counter }}">
                ${ item.slug }
              </a>
            </td>
            <td v-else>
              <a href="#" data-toggle="modal" data-target="#myModal{{ forloop.counter }}">
                ${ item.id }
              </a>
            </td>
            <td>${ item.name }</td>
            <td>${ item.full_name }</td>
            <td>
              <a :href="item.html_url" target="_blank">${ item.html_url }</a>
            </td>
            <td class="text-center">${ item.stargazers_count }</td>

            <!-- Modal -->
            <div class="modal fade" id="myModal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title">${ item.name }</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  </div>
                  <div class="modal-body">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item"><b>name:</b> ${ item.name }</li>
                      <li class="list-group-item"><b>full_name:</b> ${ item.full_name }</li>
                      <li class="list-group-item"><b>html_url:</b> ${ item.html_url }</li>
                      <li class="list-group-item"><b>stargazers_count:</b> ${ item.stargazers_count }</li>
                    </ul>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
          </tr>
        </template>
      </tbody>
    </table>

  </div>

</div>
{% endblock content %}

{% block js %}

<script src="{% static 'js/main.js' %}"></script>

{% endblock js %}

myproject/core/templates/includes/nav.html
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">API Github</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:repo_list' %}">Repositórios</a>
            </li>
        </ul>
        <!-- { if user.is_authenticated %}
                  <ul class="navbar-nav px-3">
                    <li class="nav-item text-nowrap">
                      <a href="{ url 'logout' %}" class="nav-link">Sair</a>
                    </li>
                  </ul>
                { endif %} -->
    </div>
</nav>